# Creating a release in GitHub will trigger an upload to PyPI and
# uploaded the sdist (source distribution) to the release.
name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.9"
      - name: "Install dependencies"
        run: |
          set -xe
          python3 -VV
          python3 -m site
          python3 -m pip install --upgrade pip build
      - name: "Build package"
        run: |
          python3 -m build
      - name: "Publish package to PyPI"
        uses: "pypa/gh-action-pypi-publish@release/v1"
